from decouple import config

def social_auth(request):
    GITHUB_CLIENT_ID = config("GITHUB_CLIENT_ID")
    FACEBOOK_APP_ID = config("FACEBOOK_APP_ID")
    FACEBOOK_REDIRECT_URL = config("FACEBOOK_REDIRECT_URL")
    GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")
    GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET")
    GOOGLE_REDIRECT_URL = config("GOOGLE_REDIRECT_URL")
    LINKEDIN_CLIENT_ID = config("LINKEDIN_CLIENT_ID")
    LINKEDIN_REDIRECT_URL = config("LINKEDIN_REDIRECT_URL")
    
    return {
        "GITHUB_CLIENT_ID": GITHUB_CLIENT_ID,
        "FACEBOOK_APP_ID": FACEBOOK_APP_ID,
        "FACEBOOK_REDIRECT_URL": FACEBOOK_REDIRECT_URL,
        "GOOGLE_CLIENT_ID": GOOGLE_CLIENT_ID,
        "GOOGLE_CLIENT_SECRET": GOOGLE_CLIENT_SECRET,
        "GOOGLE_REDIRECT_URL": GOOGLE_REDIRECT_URL,
        "LINKEDIN_CLIENT_ID": LINKEDIN_CLIENT_ID,
        "LINKEDIN_REDIRECT_URL": LINKEDIN_REDIRECT_URL,
        }
