# Generated by Django 5.0.3 on 2024-03-13 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(default='Aliquam varius posuere nunc, nec imperdiet neque condimentum at. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Please support us by contributing a small donation via PayPal.')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('dimension', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=20, verbose_name='Format')),
                ('license', models.TextField(default='Free for both personal and commercial use. No need to pay anything. No need to make any attribution.', verbose_name='License')),
                ('tags', models.ManyToManyField(related_name='photos', to='gallery.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(default='Aliquam varius posuere nunc, nec imperdiet neque condimentum at. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Please support us by contributing a small donation via PayPal.')),
                ('video', models.FileField(upload_to='videos//%Y/%m/%d/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('resolution', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=20, verbose_name='Format')),
                ('duration', models.DurationField()),
                ('license', models.TextField(default='Free for both personal and commercial use. No need to pay anything. No need to make any attribution.', verbose_name='License')),
                ('tags', models.ManyToManyField(related_name='videos', to='gallery.tag')),
            ],
        ),
    ]
