# Generated by Django 5.0.3 on 2024-04-01 15:41

import autoslug.fields
import cloudinary_storage.storage
import cloudinary_storage.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('image', models.ImageField(default='fallback.jpg', upload_to='category/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(default='Aliquam varius posuere nunc, nec imperdiet neque condimentum at. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Please support us by contributing a small donation via PayPal.')),
                ('photo', models.ImageField(default='fallback.jpg', upload_to='photos/%Y/%m/%d/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('dimension', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=20, verbose_name='Format')),
                ('license', models.TextField(default='Free for both personal and commercial use. No need to pay anything. No need to make any attribution.', verbose_name='License')),
                ('caption', models.CharField(default='Untitled', max_length=10, verbose_name='Caption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='photos', to='gallery.tag')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='gallery_pho_created_9eab74_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(default='Aliquam varius posuere nunc, nec imperdiet neque condimentum at. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Please support us by contributing a small donation via PayPal.')),
                ('video', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/%Y/%m/%d/', validators=[cloudinary_storage.validators.validate_video])),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('resolution', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=20, verbose_name='Format')),
                ('duration', models.CharField(default='00:00:20')),
                ('license', models.TextField(default='Free for both personal and commercial use. No need to pay anything. No need to make any attribution.', verbose_name='License')),
                ('caption', models.CharField(default='Untitled', max_length=10, verbose_name='Caption')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='videos', to='gallery.tag')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='gallery_vid_created_125e6e_idx')],
            },
        ),
    ]
