# Generated by Django 5.0.3 on 2024-03-19 11:58

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_alter_video_video_photo_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='img/fallback.jpg', upload_to='category/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='img/fallback.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='video/hero.mp4', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/%Y/%m/%d/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
