# Generated by Django 5.0.3 on 2024-04-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_photo_downloads_alter_downloadphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadphoto',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='gallery.photo'),
        ),
    ]
