# Generated by Django 5.0.3 on 2024-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_category_image_alter_photo_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='fallback.jpg', upload_to='category/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='fallback.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
