# Generated by Django 5.0.3 on 2024-03-20 11:35

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_category_image_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/%Y/%m/%d/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
