# Generated by Django 5.0.3 on 2024-04-04 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_downloadphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='downloads',
        ),
        migrations.CreateModel(
            name='DownloadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='gallery.video')),
            ],
        ),
    ]
