# Generated by Django 5.0.3 on 2024-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='Untitled', max_length=10, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(default='Untitled', max_length=10, verbose_name='Caption'),
        ),
    ]
